# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - gripper
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  # - name: hand_controller
  #   action_ns: follow_joint_trajectory
  #   default: True
  #   type: FollowJointTrajectory
  #   joints:
  #     - gripper
  #     - gripper_sub
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  gains:
    joint1: { p: 100000.0, i: 1000.0, d: 100.0, i_clamp: 0.2, antiwindup: false, publish_state: true }
    joint2: { p: 100000.0, i: 1000.0, d: 500.0, i_clamp: 0.2, antiwindup: false, publish_state: true }
    joint3: { p: 100000.0, i: 1000.0, d: 500.0, i_clamp: 0.2, antiwindup: false, publish_state: true }
    joint4: { p: 100000.0, i: 1000.0, d: 500.0, i_clamp: 0.2, antiwindup: false, publish_state: true }
gripper_position:
  type: effort_controllers/JointPositionController
  joint: gripper
  gains:
    gripper: {p: 10.0, i: 0.0, d: 1.0}
gripper_position_sub:
  type: effort_controllers/JointPositionController
  joint: gripper_sub
  gains:
    gripper: {p: 10.0, i: 0.0, d: 1.0}